arb-dir: lib/core/l10n/arb
template-arb-file: app_id.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/l10n
nullable-getter: false
synthetic-package: false